export const translations = {
  en: {
    nav: {
      about: "About",
      experience: "Experience",
      projects: "Projects",
      education: "Education",
      skills: "Skills",
      contact: "Contact",
    },
    hero: {
      location: "Cairo, Egypt • Open to Remote & Relocation",
      name: "Ahmed Gaiter",
      role: "AI Software Engineer & Backend Developer",
      bio: "I build production-grade agentic workflows with LangGraph, scalable FastAPI backends, and low-latency real-time applications. Passionate about turning complex AI research into dependable, enterprise-ready software.",
      btnProjects: "Featured Projects",
      btnResume: "Download Resume",
      btnContact: "Get in Touch",
      specialties: [
        "Stateful Multi-Agent Systems (LangGraph)",
        "High-Performance Asynchronous FastAPI",
        "Production RAG & Vector Retrieval",
        "Real-Time WebSockets & Celery Queues"
      ]
    },
    about: {
      sectionTitle: "About",
      headline: "Engineering dependable AI systems for real-world products.",
      p1: "I specialize in bridging the gap between frontier Large Language Models and resilient, high-throughput cloud infrastructure. Instead of building superficial wrappers, I focus on deterministic multi-agent state machines, dynamic tool calling, and robust failover mechanisms.",
      p2: "My core toolset revolves around Python (AsyncIO), LangGraph, FastAPI, Redis, Docker, and Kubernetes, with a disciplined commitment to clean architecture, automated testing, and sub-second response times.",
      highlights: [
        { title: "2+ Years Experience", desc: "Building production backends and AI pipelines" },
        { title: "B.Sc. in Computer Science", desc: "Mansoura University (2019 — 2023)" },
        { title: "Production Focus", desc: "Docker, Kubernetes, Redis, Celery & CI/CD" },
        { title: "AI Engineering Masterclass", desc: "Certified by Dr. Mahmoud Eid" }
      ]
    },
    experience: {
      sectionTitle: "Experience",
      headline: "Professional experience and technical contributions.",
      jobs: [
        {
          role: "AI Software Engineer & Solutions Consultant",
          company: "Contract / Remote",
          period: "Jan 2024 — Present",
          bullets: [
            "Architected and deployed production-grade RAG systems and multi-agent backend APIs using FastAPI and LangGraph for enterprise clients.",
            "Engineered multi-provider LLM fallback routing (LiteLLM across Groq, Gemini, and Anthropic) to maintain 99.9% application uptime.",
            "Built asynchronous Celery and Redis queuing pipelines to decouple heavy inference workloads, cutting synchronous API response latency by 45%.",
            "Containerized backend microservices using multi-stage Docker builds and automated continuous integration pipelines via GitHub Actions."
          ],
          skills: ["Python", "FastAPI", "LangGraph", "Redis", "Celery", "Docker", "PostgreSQL", "CI/CD"]
        },
        {
          role: "AI Systems Evaluator & Model Alignment",
          company: "Atlas Capture / Remote",
          period: "Dec 2024 — Jun 2025",
          bullets: [
            "Evaluated and stress-tested complex Python and JavaScript code generated by frontier LLMs to produce high-benchmark RLHF alignment datasets.",
            "Designed adversarial test suites to detect model hallucinations, recursive agent failure loops, and prompt injection vulnerabilities.",
            "Audited agentic tool execution trajectories to enforce deterministic execution schemas and strict Pydantic data validation."
          ],
          skills: ["RLHF", "Model Evals", "Adversarial Testing", "Python", "Pydantic", "AI Safety"]
        },
        {
          role: "AI Engineering Intern",
          company: "Springer Capital / Remote",
          period: "Jun 2025 — Aug 2025",
          bullets: [
            "Developed automated Python data synchronization pipelines and internal AI tooling to streamline quantitative research tasks.",
            "Integrated LLM-assisted document parsing to accelerate internal data extraction workflows, reducing manual processing overhead by 30%."
          ],
          skills: ["Python", "Automation", "LLM Integration", "Data Pipelines"]
        }
      ]
    },
    projects: {
      sectionTitle: "Projects",
      headline: "Featured systems with source code and live deployments.",
      viewDemo: "Live Demo",
      viewCode: "Source Code",
      items: [
        {
          title: "AutoHire",
          subtitle: "Autonomous Real-Time Technical Interview Platform",
          desc: "A real-time voice and text technical interview platform. Uses native FastAPI WebSockets and an event-driven LangGraph state machine, with background scoring decoupled via Redis and Celery to achieve sub-300ms responsiveness.",
          tags: ["FastAPI", "LangGraph", "WebSockets", "Redis", "Celery", "React"],
          demo: "https://ai-automation-interview.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-interview-automation",
          image: "/project-AutoHire1.png"
        },
        {
          title: "Shiphny AI",
          subtitle: "Enterprise Logistics Multi-Agent Support Architecture",
          desc: "A multi-agent logistics platform with deterministic LangGraph cyclic workflows, Redis session checkpointing, and an audited 5-layer prompt injection defense framework with Kubernetes deployment manifests.",
          tags: ["FastAPI", "LangGraph", "Redis", "PostgreSQL", "Docker", "Kubernetes"],
          demo: "https://shiphny-ai-support.vercel.app/",
          github: "https://github.com/ahmedgeeter/shiphny-ai-support",
          image: "/project-shiphny.png"
        },
        {
          title: "Meridian",
          subtitle: "Multimodal Industrial Inspection & Document Auditor",
          desc: "An automated data extraction and compliance engine using Meta Llama-3.2 Vision for blueprints/invoices and Whisper-Large-V3 for vocal verification and regulatory compliance auditing.",
          tags: ["React 18", "Llama 3.2 Vision", "Whisper V3", "Pydantic", "FastAPI"],
          demo: "https://ai-auditor-ocr-voice.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-auditor-ocr-voice",
          image: "/project-ai-auditor/Screenshot 2026-04-13 210744.png"
        },
        {
          title: "LLM Safety Guardrail API",
          subtitle: "Production Security Microservice for AI Workflows",
          desc: "High-performance microservice enforcing strict Pydantic output validation, prompt-injection sanitization, and automated PII anonymization before upstream LLM dispatch.",
          tags: ["FastAPI", "Pydantic V2", "Redis", "Docker", "AI Guardrails"],
          demo: null,
          github: "https://github.com/ahmedgeeter/LLM-Safety-Guardrail-API",
          image: "/project-rag.png"
        },
        {
          title: "Coremont",
          subtitle: "Full-Stack E-Commerce Assistant with Hybrid RAG",
          desc: "An intelligent e-commerce store with persistent vector memory, semantic caching backed by Redis, and exact catalog retrieval powered by Groq and PostgreSQL.",
          tags: ["Next.js", "RAG", "Vector Search", "Redis", "PostgreSQL"],
          demo: "https://fullstack-gym-rag-chatbot.vercel.app/",
          github: "https://github.com/ahmedgeeter/fullstack-gym-rag-chatbot",
          image: "/project-coremont.png"
        }
      ]
    },
    education: {
      sectionTitle: "Education & Certifications",
      headline: "Academic credentials and specialized AI training.",
      degree: {
        title: "B.Sc. in Computer Science",
        institution: "Mansoura University, Egypt",
        period: "2019 — 2023",
        desc: "Core coursework: Data Structures & Algorithms, Distributed Systems, Operating Systems, Database Management Systems, and Artificial Intelligence."
      },
      certs: [
        {
          title: "AI Engineering Masterclass",
          issuer: "Dr. Mahmoud Eid",
          period: "2024",
          badge: "Advanced Masterclass",
          desc: "Comprehensive masterclass on advanced multi-agent systems, LangGraph cyclic architectures, stateful agent checkpoints, and production LLM engineering."
        },
        {
          title: "Deep Learning: Getting Started",
          issuer: "LinkedIn Learning",
          period: "2023",
          badge: "Neural Networks",
          desc: "Foundations of neural network architecture design, backpropagation, and deep learning model evaluation."
        },
        {
          title: "Ethics in the Age of Generative AI",
          issuer: "IBM",
          period: "2024",
          badge: "AI Safety",
          desc: "Model alignment, deterministic output guardrails, bias remediation, and responsible AI deployment."
        }
      ]
    },
    skills: {
      sectionTitle: "Technical Skills",
      headline: "Core technologies and engineering proficiencies.",
      groups: [
        {
          category: "AI & Agentic Systems",
          skills: ["LangGraph (Cyclic Graphs)", "Production RAG", "Tool Calling", "LiteLLM", "Redis Checkpointing", "Groq & Gemini APIs", "Whisper", "Vision Models"]
        },
        {
          category: "Backend & Systems",
          skills: ["Python (AsyncIO)", "FastAPI", "WebSockets", "Celery", "Redis", "Pydantic V2", "SQLAlchemy", "Alembic", "RESTful APIs"]
        },
        {
          category: "DevOps & Cloud",
          skills: ["Docker & Docker Compose", "Kubernetes (EKS)", "Terraform", "GitHub Actions CI/CD", "Linux / Bash", "AWS (EC2, S3)"]
        },
        {
          category: "Databases & Frontend",
          skills: ["PostgreSQL", "Redis Caching", "FAISS / PGVector", "React 18", "Next.js", "TypeScript", "Tailwind CSS"]
        }
      ]
    },
    contact: {
      sectionTitle: "Contact",
      headline: "Let's connect and discuss how I can contribute to your team.",
      desc: "Whether you're hiring for an AI engineering role, building an agentic backend, or exploring technical collaboration — feel free to reach out directly.",
      btnEmail: "Email Me",
      btnWhatsApp: "WhatsApp",
      btnLinkedIn: "LinkedIn",
      btnResume: "Download Resume (PDF)",
      footer: "© {year} Ahmed Gaiter. Designed and developed with care."
    }
  },
  ar: {
    nav: {
      about: "عنّي",
      experience: "الخبرات",
      projects: "المشاريع",
      education: "التعليم",
      skills: "المهارات",
      contact: "التواصل",
    },
    hero: {
      location: "القاهرة، مصر • متاح للعمل عن بُعد ولفرص الانتقال",
      name: "أحمد جيتر",
      role: "مهندس برمجيات ذكاء اصطناعي وبنية تحتية خلفية",
      bio: "أبني أنظمة وكلاء ذكية جاهزة للإنتاج باستخدام LangGraph، وواجهات برمجة خلفية عالية الأداء بـ FastAPI، وتطبيقات فورية بزمن استجابة فائق السرعة. أسعى لتحويل أحدث أبحاث الذكاء الاصطناعي إلى برمجيات مؤسسية موثوقة.",
      btnProjects: "المشاريع المميزة",
      btnResume: "تحميل السيرة الذاتية",
      btnContact: "تواصل معي",
      specialties: [
        "أنظمة الوكلاء المتعددة وحفظ الحالة (LangGraph)",
        "واجهات خلفية غير متزامنة عالية الأداء (FastAPI)",
        "مسارات استرجاع متقدمة للبيانات (Production RAG)",
        "اتصال لحظي بـ WebSockets وطوابير Celery"
      ]
    },
    about: {
      sectionTitle: "نبذة عني",
      headline: "هندسة أنظمة ذكاء اصطناعي موثوقة ومبنية لخدمة المنتجات الحقيقية.",
      p1: "أتخصص في الربط بين النماذج اللغوية الكبيرة الرائدة وبين البنية التحتية الخلفية السحابية الموثوقة. بدلاً من الاعتماد على مجرد واجهات سطحية، أركز على تصميم مسارات الوكلاء الحتمية، وحفظ الحالة، واستدعاء الأدوات بدقة، مع بناء آليات توجيه احتياطي تضمن استمرارية الخدمة.",
      p2: "ترتكز أدواتي على Python (AsyncIO) و LangGraph و FastAPI و Redis و Docker و Kubernetes، مع التزام صارم بجودة الكود والاختبارات المؤتمتة وزمن استجابة أقل من ثانية.",
      highlights: [
        { title: "2+ سنوات خبرة", desc: "في بناء الواجهات الخلفية ومسارات الذكاء الاصطناعي" },
        { title: "بكالوريوس علوم الحاسب", desc: "جامعة المنصورة (2019 — 2023)" },
        { title: "جاهزية الإنتاج", desc: "Docker و Kubernetes و Redis و Celery و CI/CD" },
        { title: "ماستركلاس هندسة الـ AI", desc: "شهادة معتمدة من د. محمود عيد" }
      ]
    },
    experience: {
      sectionTitle: "الخبرات المهنية",
      headline: "المحطات المهنية والمساهمات التقنية.",
      jobs: [
        {
          role: "مهندس برمجيات ذكاء اصطناعي ومستشار حلول",
          company: "تعاقد عن بُعد",
          period: "يناير 2024 — الحاضر",
          bullets: [
            "تصميم ونشر مسارات RAG مؤسسية وواجهات خلفية للوكلاء باستخدام FastAPI و LangGraph للعملاء المباشرين.",
            "تطوير منظومة توجيه احتياطي متعددة المزودين (Groq و Gemini و Anthropic) لضمان استمرارية التطبيقات بنسبة 99.9%.",
            "بناء خطوط معالجة خلفية غير متزامنة بـ Celery و Redis لفصل المهام الثقيلة وتقليل زمن الاستجابة بنسبة 45%.",
            "حزم الخدمات البرمجية في حاويات Docker متعددة المراحل وأتمتة النشر عبر GitHub Actions."
          ],
          skills: ["Python", "FastAPI", "LangGraph", "Redis", "Celery", "Docker", "PostgreSQL", "CI/CD"]
        },
        {
          role: "مقيّم نظم ذكاء اصطناعي ومحاذاة نماذج",
          company: "Atlas Capture / عن بُعد",
          period: "ديسمبر 2024 — يونيو 2025",
          bullets: [
            "تقييم واختبار أكواد برمجية معقدة بلغات Python و JavaScript مولدة من النماذج اللغوية لتوفير بيانات محاذاة لـ RLHF.",
            "تصميم اختبارات هجومية واستباقية لاكتشاف الهلوسات ومسارات الفشل ونقاط ضعف حقن الأوامر.",
            "تدقيق استدعاءات الأدوات وفرض مطابقة صارمة للمخططات عبر مكتبة Pydantic."
          ],
          skills: ["RLHF", "Model Evals", "Adversarial Testing", "Python", "Pydantic", "AI Safety"]
        },
        {
          role: "مهندس ذكاء اصطناعي متدرب",
          company: "Springer Capital / عن بُعد",
          period: "يونيو 2025 — أغسطس 2025",
          bullets: [
            "تطوير سكربتات مزامنة بيانات مؤتمتة وأدوات ذكاء اصطناعي داخلية لتسريع أبحاث الفريق.",
            "دمج تقنيات معالجة المستندات بالنماذج اللغوية مما قلل وقت المعالجة اليدوية بنسبة 30%."
          ],
          skills: ["Python", "Automation", "LLM Integration", "Data Pipelines"]
        }
      ]
    },
    projects: {
      sectionTitle: "المشاريع",
      headline: "أنظمة برمجية متكاملة كُتبت بكود نظيف مع روابط الكود المصدري والتجربة الحية.",
      viewDemo: "تجربة حية",
      viewCode: "الكود المصدري",
      items: [
        {
          title: "AutoHire",
          subtitle: "منصة ذكية لإجراء المقابلات التقنية اللحظية",
          desc: "منصة متكاملة للمقابلات التقنية الصوتية والنصية لحظياً، مبنية على WebSockets بداخل FastAPI ومحرك حالات LangGraph، مع فصل درجات التقييم في الخلفية عبر Celery و Redis بزمن استجابة أقل من 300 مللي ثانية.",
          tags: ["FastAPI", "LangGraph", "WebSockets", "Redis", "Celery", "React"],
          demo: "https://ai-automation-interview.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-interview-automation",
          image: "/project-AutoHire1.png"
        },
        {
          title: "Shiphny AI",
          subtitle: "نظام دعم لوجستي متعدد الوكلاء للشركات",
          desc: "منصة دعم لوجستي تعتمد على وكلاء متعددين بـ LangGraph مع حفظ المحادثات على Redis، ونظام حماية خماسي الطبقات ضد الاختراق مع ملفات نشر Kubernetes جاهزة للإنتاج.",
          tags: ["FastAPI", "LangGraph", "Redis", "PostgreSQL", "Docker", "Kubernetes"],
          demo: "https://shiphny-ai-support.vercel.app/",
          github: "https://github.com/ahmedgeeter/shiphny-ai-support",
          image: "/project-shiphny.png"
        },
        {
          title: "Meridian",
          subtitle: "مُدقق مستندات وتسجيلات صوتية صناعية متعدد الوسائط",
          desc: "نظام تدقيق آلي للمستندات المعقدة والمخططات الهندسية باستخدام Meta Llama-3.2 Vision والمطابقة الصوتية عبر Whisper-Large-V3 للتحقق من الالتزام بالمعايير.",
          tags: ["React 18", "Llama 3.2 Vision", "Whisper V3", "Pydantic", "FastAPI"],
          demo: "https://ai-auditor-ocr-voice.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-auditor-ocr-voice",
          image: "/project-ai-auditor/Screenshot 2026-04-13 210744.png"
        },
        {
          title: "LLM Safety Guardrail API",
          subtitle: "خدمة أمنية لحماية وتدقيق مخرجات النماذج اللغوية",
          desc: "خدمة مصغرة عالية الأداء تفرض التحقق الصارم من صحة البيانات بـ Pydantic، وتمنع حقن الأوامر، وتخفي البيانات الحساسة (PII) قبل إرسال الطلبات للنماذج.",
          tags: ["FastAPI", "Pydantic V2", "Redis", "Docker", "AI Guardrails"],
          demo: null,
          github: "https://github.com/ahmedgeeter/LLM-Safety-Guardrail-API",
          image: "/project-rag.png"
        },
        {
          title: "Coremont",
          subtitle: "مساعد تجارة إلكترونية ذكي بتقنية RAG الهجينة",
          desc: "متجر إلكتروني ذكي يتضمن بحثاً شعاعياً للمنتجات وذاكرة تخزين مؤقت دلالية عبر Redis للإجابة الدقيقة على استفسارات الأسعار والسياسات.",
          tags: ["Next.js", "RAG", "Vector Search", "Redis", "PostgreSQL"],
          demo: "https://fullstack-gym-rag-chatbot.vercel.app/",
          github: "https://github.com/ahmedgeeter/fullstack-gym-rag-chatbot",
          image: "/project-coremont.png"
        }
      ]
    },
    education: {
      sectionTitle: "التعليم والشهادات",
      headline: "الأساس الأكاديمي والتدريب المتقدم في الذكاء الاصطناعي.",
      degree: {
        title: "بكالوريوس في علوم الحاسب",
        institution: "جامعة المنصورة، مصر",
        period: "2019 — 2023",
        desc: "المساقات الأساسية: هياكل البيانات والخوارزميات، الأنظمة الموزعة، نظم التشغيل، قواعد البيانات، والذكاء الاصطناعي."
      },
      certs: [
        {
          title: "ماستركلاس هندسة الذكاء الاصطناعي (AI Engineering Masterclass)",
          issuer: "د. محمود عيد (Dr. Mahmoud Eid)",
          period: "2024",
          badge: "تدريب تخصصي متقدم",
          desc: "برنامج تدريبي متقدم يغطي أنظمة الوكلاء المتعددة، معمارية LangGraph الحتمية، إدارة الذاكرة، وهندسة النماذج اللغوية في بيئات الإنتاج."
        },
        {
          title: "أساسيات التعلم العميق (Deep Learning: Getting Started)",
          issuer: "LinkedIn Learning",
          period: "2023",
          badge: "الشبكات العصبية",
          desc: "تصميم معمارية الشبكات العصبية، خوارزميات الانتشار العكسي، وتقييم النماذج العميقة."
        },
        {
          title: "أخلاقيات عصر الذكاء الاصطناعي التوليدي (Ethics in Generative AI)",
          issuer: "IBM",
          period: "2024",
          badge: "أمان الذكاء الاصطناعي",
          desc: "محاذاة النماذج اللغوية، بوابات الأمان، وتجنب الانحيازات في التطبيقات الواقعية."
        }
      ]
    },
    skills: {
      sectionTitle: "المهارات التقنية",
      headline: "الترسانة التقنية التي أعتمد عليها لبناء منتجات قابلة للتوسع.",
      groups: [
        {
          category: "الذكاء الاصطناعي والوكلاء",
          skills: ["LangGraph (Cyclic Graphs)", "Production RAG", "Tool Calling", "LiteLLM", "Redis Checkpointing", "Groq & Gemini APIs", "Whisper", "Vision Models"]
        },
        {
          category: "الواجهات الخلفية والأنظمة",
          skills: ["Python (AsyncIO)", "FastAPI", "WebSockets", "Celery", "Redis", "Pydantic V2", "SQLAlchemy", "Alembic", "RESTful APIs"]
        },
        {
          category: "السحابة والتشغيل (DevOps)",
          skills: ["Docker & Docker Compose", "Kubernetes (EKS)", "Terraform", "GitHub Actions CI/CD", "Linux / Bash", "AWS (EC2, S3)"]
        },
        {
          category: "قواعد البيانات والواجهات",
          skills: ["PostgreSQL", "Redis Caching", "FAISS / PGVector", "React 18", "Next.js", "TypeScript", "Tailwind CSS"]
        }
      ]
    },
    contact: {
      sectionTitle: "التواصل",
      headline: "يسعدني دائماً التواصل ومناقشة كيف يمكنني المساهمة في نجاح فريقكم.",
      desc: "سواء كنتم تبحثون عن مهندس ذكاء اصطناعي للانضمام لفريقكم، أو بناء واجهة خلفية للوكلاء الأذكياء، أو نقاش تقني — يمكنكم التواصل معي مباشرة.",
      btnEmail: "مراسلتي عبر البريد",
      btnWhatsApp: "محادثة عبر واتساب",
      btnLinkedIn: "التواصل عبر لينكد إن",
      btnResume: "تحميل السيرة الذاتية (PDF)",
      footer: "© {year} أحمد جيتر. صُمم وطُوّر بكل عناية."
    }
  }
};
