export const translations = {
  en: {
    nav: {
      about: "About",
      experience: "Experience",
      projects: "Projects",
      education: "Education",
      skills: "Skills",
      contact: "Contact",
    },
    hero: {
      status: "Available for full-time & high-impact contract roles",
      greeting: "Hi, I'm Ahmed Gaiter",
      title: "AI Software Engineer & Backend Developer",
      subtitle: "I design and build production-grade agentic workflows with LangGraph, scalable FastAPI backends, and low-latency real-time applications. Based in Cairo, working with global teams.",
      btnProjects: "View My Work",
      btnResume: "Download Resume",
      btnContact: "Get in Touch",
    },
    about: {
      sectionTitle: "About Me",
      headline: "Engineering dependable AI systems for real-world products.",
      p1: "I specialize in bridging frontier Large Language Models with reliable, high-throughput cloud backends. Rather than relying on simple wrappers, I focus on building robust multi-agent state machines, deterministic tool calling, and resilient failover infrastructure.",
      p2: "My core toolset revolves around Python (AsyncIO), LangGraph, FastAPI, Redis, Docker, and Kubernetes, with a strong commitment to clean architecture, automated testing, and sub-second response times.",
    },
    experience: {
      sectionTitle: "Work Experience",
      headline: "Where I've contributed and what I've delivered.",
      jobs: [
        {
          role: "AI Software Engineer & Solutions Consultant",
          company: "Contract / Remote",
          period: "Jan 2024 — Present",
          bullets: [
            "Architected and deployed production RAG pipelines and multi-agent backend APIs using FastAPI and LangGraph for enterprise clients.",
            "Engineered multi-provider LLM fallback routing (LiteLLM across Groq, Gemini, and Anthropic) to maintain 99.9% application uptime.",
            "Built asynchronous Celery and Redis queuing pipelines to decouple long-running inferences, cutting synchronous API response latency by 45%.",
            "Containerized backend microservices using Docker and established CI/CD pipelines via GitHub Actions."
          ],
          skills: ["Python", "FastAPI", "LangGraph", "Redis", "Celery", "Docker", "PostgreSQL"]
        },
        {
          role: "AI Systems Evaluator & Model Alignment",
          company: "Atlas Capture / Remote",
          period: "Dec 2024 — Jun 2025",
          bullets: [
            "Evaluated and stress-tested complex Python and JavaScript code generated by frontier LLMs to produce high-benchmark RLHF alignment datasets.",
            "Designed adversarial test cases to detect model hallucinations, recursive agent failure states, and prompt injection vulnerabilities.",
            "Validated agentic tool-use trajectories to enforce deterministic execution schemas and strict Pydantic validation."
          ],
          skills: ["LLM Evals", "RLHF", "Adversarial Testing", "Python", "Pydantic", "AI Safety"]
        },
        {
          role: "AI Engineering Intern",
          company: "Springer Capital / Remote",
          period: "Jun 2025 — Aug 2025",
          bullets: [
            "Developed automated Python data synchronization scripts and internal AI tooling to streamline research workflows.",
            "Integrated LLM-assisted document parsing to accelerate data extraction pipelines, reducing manual processing time by 30%."
          ],
          skills: ["Python", "Automation", "LLM Integration", "Agile"]
        }
      ]
    },
    projects: {
      sectionTitle: "Featured Projects",
      headline: "Real-world systems built with clean code and tested architecture.",
      viewDemo: "Live Demo",
      viewCode: "Source Code",
      items: [
        {
          title: "AutoHire",
          subtitle: "Autonomous Real-Time Technical Interview Platform",
          desc: "A full-duplex voice and text technical interview platform. Uses native FastAPI WebSockets and an event-driven LangGraph state machine, with background scoring decoupled via Redis and Celery to achieve sub-300ms latency.",
          tags: ["FastAPI", "LangGraph", "WebSockets", "Redis", "Celery", "React"],
          demo: "https://ai-automation-interview.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-interview-automation",
          image: "/project-AutoHire1.png"
        },
        {
          title: "Shiphny AI",
          subtitle: "Enterprise Logistics Multi-Agent Support Architecture",
          desc: "A multi-agent logistics platform with deterministic LangGraph cyclic workflows, Redis session checkpointing, and an audited 5-layer prompt injection defense framework with Kubernetes deployment manifests.",
          tags: ["FastAPI", "LangGraph", "Redis", "PostgreSQL", "Docker", "Kubernetes"],
          demo: "https://shiphny-ai-support.vercel.app/",
          github: "https://github.com/ahmedgeeter/shiphny-ai-support",
          image: "/project-shiphny.png"
        },
        {
          title: "Meridian",
          subtitle: "Multimodal Industrial Inspection & Document Auditor",
          desc: "An automated data extraction and compliance engine using Meta Llama-3.2 Vision for blueprints/invoices and Whisper-Large-V3 for vocal verification and regulatory compliance auditing.",
          tags: ["React 18", "Llama 3.2 Vision", "Whisper V3", "Pydantic", "FastAPI"],
          demo: "https://ai-auditor-ocr-voice.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-auditor-ocr-voice",
          image: "/project-ai-auditor/Screenshot 2026-04-13 210744.png"
        },
        {
          title: "LLM Safety Guardrail API",
          subtitle: "Production Security Microservice for AI Workflows",
          desc: "High-performance microservice enforcing strict Pydantic output validation, prompt-injection sanitization, and automated PII anonymization before upstream LLM dispatch.",
          tags: ["FastAPI", "Pydantic V2", "Redis", "Docker", "AI Guardrails"],
          demo: null,
          github: "https://github.com/ahmedgeeter/LLM-Safety-Guardrail-API",
          image: "/project-rag.png"
        },
        {
          title: "Coremont",
          subtitle: "Full-Stack E-Commerce Assistant with Hybrid RAG",
          desc: "An intelligent e-commerce store with persistent vector memory, semantic caching backed by Redis, and exact catalog retrieval powered by Groq and PostgreSQL.",
          tags: ["Next.js", "RAG", "Vector Search", "Redis", "PostgreSQL"],
          demo: "https://fullstack-gym-rag-chatbot.vercel.app/",
          github: "https://github.com/ahmedgeeter/fullstack-gym-rag-chatbot",
          image: "/project-coremont.png"
        }
      ]
    },
    education: {
      sectionTitle: "Education & Certifications",
      headline: "Academic foundation and specialized AI credentials.",
      degree: {
        title: "B.Sc. in Computer Science",
        institution: "Mansoura University, Egypt",
        period: "2019 — 2023",
        desc: "Core curriculum: Data Structures & Algorithms, Distributed Systems, Operating Systems, Database Management Systems, and Artificial Intelligence."
      },
      certs: [
        {
          title: "AI Engineering Masterclass",
          issuer: "Dr. Mahmoud Eid",
          period: "2024",
          badge: "Specialized Masterclass",
          desc: "Comprehensive masterclass on advanced multi-agent systems, LangGraph cyclic architectures, stateful agent checkpoints, and production LLM engineering."
        },
        {
          title: "Deep Learning: Getting Started",
          issuer: "LinkedIn Learning",
          period: "2023",
          badge: "Neural Networks",
          desc: "Foundations of neural network architecture design, backpropagation, and deep learning model evaluation."
        },
        {
          title: "Ethics in the Age of Generative AI",
          issuer: "IBM",
          period: "2024",
          badge: "AI Safety",
          desc: "Model alignment, deterministic output guardrails, bias remediation, and responsible AI deployment."
        }
      ]
    },
    skills: {
      sectionTitle: "Technical Skills",
      headline: "The technologies I use to build scalable products.",
      groups: [
        {
          category: "AI & Agentic Systems",
          skills: ["LangGraph (Cyclic Graphs)", "Production RAG", "Tool Calling", "LiteLLM", "Redis Checkpointing", "Groq & Gemini APIs", "Whisper", "Vision Models"]
        },
        {
          category: "Backend & Systems",
          skills: ["Python (AsyncIO)", "FastAPI", "WebSockets", "Celery", "Redis", "Pydantic V2", "SQLAlchemy", "Alembic", "RESTful APIs"]
        },
        {
          category: "DevOps & Cloud",
          skills: ["Docker & Docker Compose", "Kubernetes (EKS)", "Terraform", "GitHub Actions CI/CD", "Linux / Bash", "AWS (EC2, S3)"]
        },
        {
          category: "Databases & Frontend",
          skills: ["PostgreSQL", "Redis Caching", "FAISS / PGVector", "React 18", "Next.js", "TypeScript", "Tailwind CSS"]
        }
      ]
    },
    contact: {
      sectionTitle: "Get In Touch",
      headline: "Let's build something exceptional together.",
      desc: "Whether you're looking for an AI engineer to join your team, need help building an agentic backend, or want to discuss a project — I'd love to hear from you.",
      btnEmail: "Send an Email",
      btnWhatsApp: "Chat on WhatsApp",
      btnLinkedIn: "Connect on LinkedIn",
      btnResume: "Download Resume (PDF)",
      footer: "© {year} Ahmed Gaiter. Designed and developed with care."
    }
  },
  ar: {
    nav: {
      about: "عنّي",
      experience: "الخبرات",
      projects: "المشاريع",
      education: "التعليم",
      skills: "المهارات",
      contact: "التواصل",
    },
    hero: {
      status: "متاح للانضمام لفرق العمل والفرص التعاقدية",
      greeting: "أهلاً، أنا أحمد جيتر",
      title: "مهندس برمجيات ذكاء اصطناعي وبنية تحتية خلفية",
      subtitle: "أصمم وأبني أنظمة وكلاء ذكية جاهزة للإنتاج باستخدام LangGraph، وواجهات برمجة خلفية عالية الأداء بـ FastAPI، وتطبيقات فورية بزمن استجابة فائق السرعة. أقيم في القاهرة وأعمل مع فرق عالمية.",
      btnProjects: "تصفح مشاريعي",
      btnResume: "تحميل السيرة الذاتية",
      btnContact: "تواصل معي",
    },
    about: {
      sectionTitle: "نبذة عني",
      headline: "بناء أنظمة ذكاء اصطناعي موثوقة ومبنية لخدمة المنتجات الحقيقية.",
      p1: "أتخصص في الربط بين النماذج اللغوية الكبيرة الرائدة وبين البنية التحتية الخلفية السحابية الموثوقة. بدلاً من الاعتماد على مجرد استدعاءات سطحية، أركز على تصميم مسارات الوكلاء الحتمية، وحفظ الحالة، واستدعاء الأدوات بدقة، مع بناء آليات توجيه احتياطي تمنع التوقف.",
      p2: "ترتكز أدواتي اليومية على Python (AsyncIO) و LangGraph و FastAPI و Redis و Docker و Kubernetes، مع التزام صارم بجودة الكود والاختبارات المؤتمتة وزمن استجابة أقل من ثانية.",
    },
    experience: {
      sectionTitle: "الخبرات المهنية",
      headline: "المحطات المهنية والقيمة التي أضفتها.",
      jobs: [
        {
          role: "مهندس برمجيات ذكاء اصطناعي ومستشار حلول",
          company: "تعاقد عن بُعد",
          period: "يناير 2024 — الحاضر",
          bullets: [
            "تصميم ونشر مسارات RAG مؤسسية وواجهات خلفية للوكلاء باستخدام FastAPI و LangGraph للعملاء المباشرين.",
            "تطوير منظومة توجيه احتياطي متعددة المزودين (Groq و Gemini و Anthropic) لضمان استمرارية التطبيقات بنسبة 99.9%.",
            "بناء خطوط معالجة خلفية غير متزامنة بـ Celery و Redis لفصل المهام الثقيلة وتقليل زمن الاستجابة بنسبة 45%.",
            "حزم الخدمات البرمجية في حاويات Docker وأتمتة النشر عبر GitHub Actions."
          ],
          skills: ["Python", "FastAPI", "LangGraph", "Redis", "Celery", "Docker", "PostgreSQL"]
        },
        {
          role: "مقيّم نظم ذكاء اصطناعي ومحاذاة نماذج",
          company: "Atlas Capture / عن بُعد",
          period: "ديسمبر 2024 — يونيو 2025",
          bullets: [
            "تقييم واختبار أكواد برمجية معقدة بلغات Python و JavaScript مولدة من النماذج اللغوية لتوفير بيانات محاذاة لـ RLHF.",
            "تصميم اختبارات هجومية واستباقية لاكتشاف الهلوسات ومسارات الفشل ونقاط ضعف حقن الأوامر.",
            "تدقيق استدعاءات الأدوات وفرض مطابقة صارمة للمخططات عبر مكتبة Pydantic."
          ],
          skills: ["LLM Evals", "RLHF", "Adversarial Testing", "Python", "Pydantic", "AI Safety"]
        },
        {
          role: "مهندس ذكاء اصطناعي متدرب",
          company: "Springer Capital / عن بُعد",
          period: "يونيو 2025 — أغسطس 2025",
          bullets: [
            "تطوير سكربتات مزامنة بيانات مؤتمتة وأدوات ذكاء اصطناعي داخلية لتسريع أبحاث الفريق.",
            "دمج تقنيات معالجة المستندات بالنماذج اللغوية مما قلل وقت المعالجة اليدوية بنسبة 30%."
          ],
          skills: ["Python", "Automation", "LLM Integration", "Agile"]
        }
      ]
    },
    projects: {
      sectionTitle: "أبرز المشاريع",
      headline: "أنظمة برمجية متكاملة كُتبت بكود نظيف وتصميم هندسي مدروس.",
      viewDemo: "تجربة حية",
      viewCode: "الكود المصدري",
      items: [
        {
          title: "AutoHire",
          subtitle: "منصة ذكية لإجراء المقابلات التقنية اللحظية",
          desc: "منصة متكاملة للمقابلات التقنية الصوتية والنصية لحظياً، مبنية على WebSockets بداخل FastAPI ومحرك حالات LangGraph، مع فصل درجات التقييم في الخلفية عبر Celery و Redis بزمن استجابة أقل من 300 مللي ثانية.",
          tags: ["FastAPI", "LangGraph", "WebSockets", "Redis", "Celery", "React"],
          demo: "https://ai-automation-interview.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-interview-automation",
          image: "/project-AutoHire1.png"
        },
        {
          title: "Shiphny AI",
          subtitle: "نظام دعم لوجستي متعدد الوكلاء للشركات",
          desc: "منصة دعم لوجستي تعتمد على وكلاء متعددين بـ LangGraph مع حفظ المحادثات على Redis، ونظام حماية خماسي الطبقات ضد الاختراق مع ملفات نشر Kubernetes جاهزة للإنتاج.",
          tags: ["FastAPI", "LangGraph", "Redis", "PostgreSQL", "Docker", "Kubernetes"],
          demo: "https://shiphny-ai-support.vercel.app/",
          github: "https://github.com/ahmedgeeter/shiphny-ai-support",
          image: "/project-shiphny.png"
        },
        {
          title: "Meridian",
          subtitle: "مُدقق مستندات وتسجيلات صوتية صناعية متعدد الوسائط",
          desc: "نظام تدقيق آلي للمستندات المعقدة والمخططات الهندسية باستخدام Meta Llama-3.2 Vision والمطابقة الصوتية عبر Whisper-Large-V3 للتحقق من الالتزام بالمعايير.",
          tags: ["React 18", "Llama 3.2 Vision", "Whisper V3", "Pydantic", "FastAPI"],
          demo: "https://ai-auditor-ocr-voice.vercel.app/",
          github: "https://github.com/ahmedgeeter/ai-auditor-ocr-voice",
          image: "/project-ai-auditor/Screenshot 2026-04-13 210744.png"
        },
        {
          title: "LLM Safety Guardrail API",
          subtitle: "خدمة أمنية لحماية وتدقيق مخرجات النماذج اللغوية",
          desc: "خدمة مصغرة عالية الأداء تفرض التحقق الصارم من صحة البيانات بـ Pydantic، وتمنع حقن الأوامر، وتخفي البيانات الحساسة (PII) قبل إرسال الطلبات للنماذج.",
          tags: ["FastAPI", "Pydantic V2", "Redis", "Docker", "AI Guardrails"],
          demo: null,
          github: "https://github.com/ahmedgeeter/LLM-Safety-Guardrail-API",
          image: "/project-rag.png"
        },
        {
          title: "Coremont",
          subtitle: "مساعد تجارة إلكترونية ذكي بتقنية RAG الهجينة",
          desc: "متجر إلكتروني ذكي يتضمن بحثاً شعاعياً للمنتجات وذاكرة تخزين مؤقت دلالية عبر Redis للإجابة الدقيقة على استفسارات الأسعار والسياسات.",
          tags: ["Next.js", "RAG", "Vector Search", "Redis", "PostgreSQL"],
          demo: "https://fullstack-gym-rag-chatbot.vercel.app/",
          github: "https://github.com/ahmedgeeter/fullstack-gym-rag-chatbot",
          image: "/project-coremont.png"
        }
      ]
    },
    education: {
      sectionTitle: "التعليم والشهادات",
      headline: "الأساس الأكاديمي والشهادات التخصصية في الذكاء الاصطناعي.",
      degree: {
        title: "بكالوريوس في علوم الحاسب",
        institution: "جامعة المنصورة، مصر",
        period: "2019 — 2023",
        desc: "المساقات الأساسية: هياكل البيانات والخوارزميات، الأنظمة الموزعة، نظم التشغيل، قواعد البيانات، والذكاء الاصطناعي."
      },
      certs: [
        {
          title: "ماستركلاس هندسة الذكاء الاصطناعي (AI Engineering Masterclass)",
          issuer: "د. محمود عيد (Dr. Mahmoud Eid)",
          period: "2024",
          badge: "شهادة تخصصية متقدمة",
          desc: "برنامج تدريبي متقدم يغطي أنظمة الوكلاء المتعددة، معمارية LangGraph الحتمية، إدارة الذاكرة، وهندسة النماذج اللغوية في بيئات الإنتاج."
        },
        {
          title: "أساسيات التعلم العميق (Deep Learning: Getting Started)",
          issuer: "LinkedIn Learning",
          period: "2023",
          badge: "الشبكات العصبية",
          desc: "تصميم معمارية الشبكات العصبية، خوارزميات الانتشار العكسي، وتقييم النماذج العميقة."
        },
        {
          title: "أخلاقيات عصر الذكاء الاصطناعي التوليدي (Ethics in Generative AI)",
          issuer: "IBM",
          period: "2024",
          badge: "أمان الذكاء الاصطناعي",
          desc: "محاذاة النماذج اللغوية، بوابات الأمان، وتجنب الانحيازات في التطبيقات الواقعية."
        }
      ]
    },
    skills: {
      sectionTitle: "المهارات التقنية",
      headline: "التقنيات التي أعتمد عليها لبناء منتجات قابلة للتوسع.",
      groups: [
        {
          category: "الذكاء الاصطناعي والوكلاء",
          skills: ["LangGraph (Cyclic Graphs)", "Production RAG", "Tool Calling", "LiteLLM", "Redis Checkpointing", "Groq & Gemini APIs", "Whisper", "Vision Models"]
        },
        {
          category: "الواجهات الخلفية والأنظمة",
          skills: ["Python (AsyncIO)", "FastAPI", "WebSockets", "Celery", "Redis", "Pydantic V2", "SQLAlchemy", "Alembic", "RESTful APIs"]
        },
        {
          category: "السحابة والتشغيل (DevOps)",
          skills: ["Docker & Docker Compose", "Kubernetes (EKS)", "Terraform", "GitHub Actions CI/CD", "Linux / Bash", "AWS (EC2, S3)"]
        },
        {
          category: "قواعد البيانات والواجهات",
          skills: ["PostgreSQL", "Redis Caching", "FAISS / PGVector", "React 18", "Next.js", "TypeScript", "Tailwind CSS"]
        }
      ]
    },
    contact: {
      sectionTitle: "تواصل معي",
      headline: "لنبدأ نقاشاً حول كيف يمكنني إضافة قيمة لفريقكم.",
      desc: "سواء كنتم تبحثون عن مهندس ذكاء اصطناعي للانضمام لفريقكم، أو تحتاجون لبناء بنية خلفية للوكلاء الأذكياء — يسعدني دائماً التواصل والحديث معكم.",
      btnEmail: "إرسال إيميل",
      btnWhatsApp: "محادثة عبر واتساب",
      btnLinkedIn: "التواصل عبر لينكد إن",
      btnResume: "تحميل السيرة الذاتية (PDF)",
      footer: "© {year} أحمد جيتر. صُمم وطُوّر بكل عناية."
    }
  }
};
